server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost/crudsqldb?createDatabaseIfNotExist=true
    username: root
    password: Monu@9134
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

